### ISSUE TITLE
Found one Java-level deadlock:

### ISSUE THREAD

**Issue by umeshkvguptha** [gwinstanley/DBPool#4]
Hi, we are using DBPool5.0 in our application and we are seeing deadlock in peak hours. Please could you help us in this regard.

Found one Java-level deadlock:
=============================
"http-83-150":
  waiting to lock monitor 0x000000000ba01938 (object 0x00000007406d90f8, a snaq.db.ConnectionPool),
  which is held by "Finalizer"
"Finalizer":
  waiting to lock monitor 0x0000000010215d00 (object 0x00000007465ba6d8, a java.util.HashMap),
  which is held by "http-83-10"
"http-83-10":
  waiting to lock monitor 0x000000001045abe8 (object 0x00000007465bb6b8, a java.util.ArrayList),
  which is held by "Finalizer"

Java stack information for the threads listed above:
===================================================
"http-83-150":
	at snaq.util.ObjectPool.checkOut(ObjectPool.java:286)
	- waiting to lock <0x00000007406d90f8> (a snaq.db.ConnectionPool)
	at snaq.db.ConnectionPool.getConnection(ConnectionPool.java:324)

"Finalizer":
	at snaq.db.CacheConnection.statementClosed(CacheConnection.java:534)
	- waiting to lock <0x00000007465ba6d8> (a java.util.HashMap)
	at snaq.db.CachedStatement.close(CachedStatement.java:133)
	at snaq.db.CacheConnection.recycle(CacheConnection.java:657)
	- locked <0x00000007465bb6b8> (a java.util.ArrayList)
	at snaq.util.ObjectPool.checkIn(ObjectPool.java:448)
	- locked <0x00000007406d90f8> (a snaq.db.ConnectionPool)
	at snaq.db.ConnectionPool.freeConnection(ConnectionPool.java:387)
	at snaq.db.CacheConnection.close(CacheConnection.java:724)

"http-83-10":
	at snaq.db.CacheConnection.statementClosed(CacheConnection.java:536)
	- waiting to lock <0x00000007465bb6b8> (a java.util.ArrayList)
	- locked <0x00000007465ba6d8> (a java.util.HashMap)
	at snaq.db.CachedStatement.close(CachedStatement.java:133)

Found 1 deadlock.

**Comment by gwinstanley** [comment]
Sorry to hear you're having problems with it. Could you provide more information to help diagnose the problem, such as which Java platform, database server type/version, pooling parameters, log traces, etc. From what you've provided the current state of the pool is not clear, making it impossible to properly diagnose the issue.

I presume you're using v5.0 for a goo reason, such as an older Java platform. If not, then I strongly recommend you upgrade. Otherwise it would be comparatively simple (although rather tedious) to back-port the latest version for Java 6 from the source, which would provide the latest updates, and possibly fix the issues.
